# Generated by Django 3.2.15 on 2023-05-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20230530_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='client',
            field=models.CharField(default='Anonymous', max_length=120),
        ),
        migrations.AddField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2023-05-30 15:16'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default='2023-05-30 15:16'),
        ),
    ]
